// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.
import './user.dart' as $user show User;


class Page {
	
	int page = 0;
	
	int perPage = 0;
	
	int total = 0;
	
	
	Future<List<user.User>,  > fetchUser() async {
		
	}
	
	Page();
	Map<String, dynamic> toJson() {
		return {
			
			"page": page,
			
			"perPage": perPage,
			
			"total": total,
			
		};
	}
	Page.fromJson(Map<String, dynamic> json) {
		
		page = json["page"];
		
		perPage = json["perPage"];
		
		total = json["total"];
		
	}
}


