// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.


class Role {
	
	int id = 0;
	
	String name = "";
	
	
	Future<void> saveRole() async {
		
	}
	
	Role();
	Map<String, dynamic> toJson() {
		return {
			
			"id": id,
			
			"name": name,
			
		};
	}
	Role.fromJson(Map<String, dynamic> json) {
		
		id = json["id"];
		
		name = json["name"];
		
	}
}


