// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.

class User {
	
	int id = 0;
	
	String name = "";
	
	String email = "";
	
	int age = 0;
	
	
	Future<String > tableName() async {
		
	}
	
	Future<int > getId() async {
		
	}
	
	Future<void> setId(int id, ) async {
		
	}
	
}


