// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.
import './role.dart' as $role show Role;

class Auth {
  String username = "";

  String password = "";

  Future<User?> login() async {}

  Auth();
  Map<String, dynamic> toJson() {
    return {
      "username": username,
      "password": password,
    };
  }

  Auth.fromJson(Map<String, dynamic> json) {
    username = json["username"];

    password = json["password"];
  }
}

class User {
  int id = 0;

  String username = "";

  String email = "";

  List<UserProfile> profiles = [];

  Future<void> save() async {}

  Future<void> addRole(
    $role.Role? role,
  ) async {}

  User();
  Map<String, dynamic> toJson() {
    return {
      "id": id,
      "username": username,
      "email": email,
      "profiles": profiles.map((e) => e.toJson()).toList(),
    };
  }

  User.fromJson(Map<String, dynamic> json) {
    id = json["id"];

    username = json["username"];

    email = json["email"];

    profiles = json["profiles"] == null
        ? []
        : json["profiles"].map((e) => UserProfile.fromJson(e)).toList();
  }
}

class UserProfile {
  String phoneNo = "";

  Future<void> save() async {}

  UserProfile();
  Map<String, dynamic> toJson() {
    return {
      "phoneNo": phoneNo,
    };
  }

  UserProfile.fromJson(Map<String, dynamic> json) {
    phoneNo = json["phoneNo"];
  }
}

class UserRole {
  int id = 0;

  User? user;

  $role.Role? role;

  Future<void> save() async {}

  UserRole();
  Map<String, dynamic> toJson() {
    return {
      "id": id,
      "user": user != null ? user!.toJson() : null,
      "role": role != null ? role!.toJson() : null,
    };
  }

  UserRole.fromJson(Map<String, dynamic> json) {
    id = json["id"];

    user = json["user"] == null ? User() : User.fromJson(json["user"]);

    role =
        json["role"] == null ? $role.Role() : $role.Role.fromJson(json["role"]);
  }
}
