// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.

struct UserRole {
	
	var id: UInt64;
	
	var user: ;
	
	var role: ;
	
	
	func save() -> Void {
		
	}
	
}

struct Auth {
	
	var id: String;
	
	var username: String;
	
	var password: String;
	
	
	func signin() -> ,   {
		
	}
	
	func signup() -> ,   {
		
	}
	
}

struct User {
	
	var id: String;
	
	var username: String;
	
	var email: String;
	
	var profiles: ;
	
	
	func save() -> Void {
		
	}
	
	func addRole(role: , ) -> Void {
		
	}
	
}

struct UserProfile {
	
	var phoneNo: String;
	
	
	func save() -> Void {
		
	}
	
}

