// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.
import { User } from './user';


export interface Page {
	
	page: number;
	
	perPage: number;
	
	total: number;
	
	
	fetchUser(): Promise<User[]> ;
	
}



export function Page(): Page {
	
	return {
		
		

		page: 0,
		

		perPage: 0,
		

		total: 0,
		

		

		fetchUser(): Promise<User[]>  {
			
			return postPage(this, 'fetch-user', {  }).then((res: { data: any }) => res.data as User[]);
			
		},
		
		
	};
	
}

// post data by restful api

function postPage(page: Page, method: string, args: {}): Promise<any> {
	const xhr = new XMLHttpRequest();
	xhr.open("POST", `/page/page/${method}`, true);
	xhr.setRequestHeader("Content-Type", "application/json");
	return new Promise((resolve, reject) => {
		xhr.onload = () => {
			if (xhr.status === 200) {
				resolve(xhr.response);
			} else {
				reject(new Error(xhr.statusText));
			}
		};
		xhr.onerror = () => {
			reject(new Error(xhr.statusText));
		};
		xhr.send(JSON.stringify({ data: page, args }));
	});
}

