// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.


export interface Role {
	
	id: string;
	
	name: string;
	
	
	save(): Promise<void>;
	
}



export function Role(): Role {
	
	return {
		
		id: "",
		
		name: "",
		
		
		save(): Promise<void> {
			
			return postRole(this, 'save', {  });
			
		},
		
		
	};
	
}

// post data by restful api

function postRole(role: Role, method: string, args: {}): Promise<any> {
	const xhr = new XMLHttpRequest();
	xhr.open("POST", `/role//role/role/${method}`, true);
	xhr.setRequestHeader("Content-Type", "application/json");
	return new Promise((resolve, reject) => {
		xhr.onload = () => {
			if (xhr.status === 200) {
				resolve(xhr.response);
			} else {
				reject(new Error(xhr.statusText));
			}
		};
		xhr.onerror = () => {
			reject(new Error(xhr.statusText));
		};
		xhr.send(JSON.stringify({ data: role, args }));
	});
}

