// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.

struct User {
	
	var id: Int64;
	
	var name: String;
	
	var email: String;
	
	var age: Int;
	
	
	func tableName() -> String,   {
		
	}
	
	func getId() -> Int64,   {
		
	}
	
	func setId(id: Int64, ) -> Void {
		
	}
	
}

