// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.

import { Injectable } from '@angular/core';
import { UserPermission, Permission, RolePermission,  } from './permission.model';
import { UserService  } from './user.service';
import { RoleService  } from './role.service';

import { _HttpClient } from '@delon/theme';

@Injectable({
	providedIn: 'root'
})
export class PermissionService {
  
	constructor(
		private http: _HttpClient,
		private userSrv: UserService,
		private roleSrv: RoleService,
		
		) { }

	
	newUserPermission(): UserPermission {
		return new UserPermission(this.http);
	}
	newPermission(): Permission {
		return new Permission(this.http);
	}
	newRolePermission(): RolePermission {
		return new RolePermission(this.http);
	}
}
