// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.
import { Role } from './role.model';

import { Injectable } from '@angular/core';
import { Auth, UserProfile, UserRole, User,  } from './user.model';
import { RoleService  } from './role.service';

import { _HttpClient } from '@delon/theme';

@Injectable({
	providedIn: 'root'
})
export class UserService {
  
	constructor(
		private http: _HttpClient,
		private roleSrv: RoleService,
		
		) { }

	
	newAuth(): Auth {
		return new Auth(this.http);
	}
	newUserProfile(): UserProfile {
		return new UserProfile(this.http);
	}
	newUserRole(): UserRole {
		return new UserRole(this.http);
	}
	/**
	* User is the user model
	*/
	newUser(): User {
		return new User(this.http);
	}
}
