// 定义所有错误详情

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: errz/v1/errz.proto

package errz_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerError_ErrorType int32

const (
	ServerError_OS       ServerError_ErrorType = 0
	ServerError_DB       ServerError_ErrorType = 1
	ServerError_INTERNAL ServerError_ErrorType = 2
	ServerError_UNKOWN   ServerError_ErrorType = 10
)

// Enum value maps for ServerError_ErrorType.
var (
	ServerError_ErrorType_name = map[int32]string{
		0:  "OS",
		1:  "DB",
		2:  "INTERNAL",
		10: "UNKOWN",
	}
	ServerError_ErrorType_value = map[string]int32{
		"OS":       0,
		"DB":       1,
		"INTERNAL": 2,
		"UNKOWN":   10,
	}
)

func (x ServerError_ErrorType) Enum() *ServerError_ErrorType {
	p := new(ServerError_ErrorType)
	*p = x
	return p
}

func (x ServerError_ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerError_ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_errz_v1_errz_proto_enumTypes[0].Descriptor()
}

func (ServerError_ErrorType) Type() protoreflect.EnumType {
	return &file_errz_v1_errz_proto_enumTypes[0]
}

func (x ServerError_ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerError_ErrorType.Descriptor instead.
func (ServerError_ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_errz_v1_errz_proto_rawDescGZIP(), []int{1, 0}
}

type AuthError_ErrorType int32

const (
	AuthError_TOKEN_EXPIRED    AuthError_ErrorType = 0
	AuthError_TOKEN_INVALID    AuthError_ErrorType = 1
	AuthError_TOKEN_NOT_FOUND  AuthError_ErrorType = 2
	AuthError_DEVICE_NOT_MATCH AuthError_ErrorType = 10
	AuthError_DEVICE_NOT_FOUND AuthError_ErrorType = 11
	AuthError_PASSWORD_INVALID AuthError_ErrorType = 20
)

// Enum value maps for AuthError_ErrorType.
var (
	AuthError_ErrorType_name = map[int32]string{
		0:  "TOKEN_EXPIRED",
		1:  "TOKEN_INVALID",
		2:  "TOKEN_NOT_FOUND",
		10: "DEVICE_NOT_MATCH",
		11: "DEVICE_NOT_FOUND",
		20: "PASSWORD_INVALID",
	}
	AuthError_ErrorType_value = map[string]int32{
		"TOKEN_EXPIRED":    0,
		"TOKEN_INVALID":    1,
		"TOKEN_NOT_FOUND":  2,
		"DEVICE_NOT_MATCH": 10,
		"DEVICE_NOT_FOUND": 11,
		"PASSWORD_INVALID": 20,
	}
)

func (x AuthError_ErrorType) Enum() *AuthError_ErrorType {
	p := new(AuthError_ErrorType)
	*p = x
	return p
}

func (x AuthError_ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthError_ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_errz_v1_errz_proto_enumTypes[1].Descriptor()
}

func (AuthError_ErrorType) Type() protoreflect.EnumType {
	return &file_errz_v1_errz_proto_enumTypes[1]
}

func (x AuthError_ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthError_ErrorType.Descriptor instead.
func (AuthError_ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_errz_v1_errz_proto_rawDescGZIP(), []int{2, 0}
}

// 数据验证相关错误
type ValidateError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field     string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message   string `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	EnMessage string `protobuf:"bytes,11,opt,name=en_message,json=enMessage,proto3" json:"en_message,omitempty"`
}

func (x *ValidateError) Reset() {
	*x = ValidateError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errz_v1_errz_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateError) ProtoMessage() {}

func (x *ValidateError) ProtoReflect() protoreflect.Message {
	mi := &file_errz_v1_errz_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateError.ProtoReflect.Descriptor instead.
func (*ValidateError) Descriptor() ([]byte, []int) {
	return file_errz_v1_errz_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidateError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidateError) GetEnMessage() string {
	if x != nil {
		return x.EnMessage
	}
	return ""
}

// 数据验证相关错误
type ServerError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      ServerError_ErrorType `protobuf:"varint,1,opt,name=type,proto3,enum=errz.v1.ServerError_ErrorType" json:"type,omitempty"`
	Message   string                `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	EnMessage string                `protobuf:"bytes,11,opt,name=en_message,json=enMessage,proto3" json:"en_message,omitempty"`
}

func (x *ServerError) Reset() {
	*x = ServerError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errz_v1_errz_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerError) ProtoMessage() {}

func (x *ServerError) ProtoReflect() protoreflect.Message {
	mi := &file_errz_v1_errz_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerError.ProtoReflect.Descriptor instead.
func (*ServerError) Descriptor() ([]byte, []int) {
	return file_errz_v1_errz_proto_rawDescGZIP(), []int{1}
}

func (x *ServerError) GetType() ServerError_ErrorType {
	if x != nil {
		return x.Type
	}
	return ServerError_OS
}

func (x *ServerError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServerError) GetEnMessage() string {
	if x != nil {
		return x.EnMessage
	}
	return ""
}

// 数据验证相关错误
type AuthError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      AuthError_ErrorType `protobuf:"varint,1,opt,name=type,proto3,enum=errz.v1.AuthError_ErrorType" json:"type,omitempty"`
	Message   string              `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	EnMessage string              `protobuf:"bytes,11,opt,name=en_message,json=enMessage,proto3" json:"en_message,omitempty"`
}

func (x *AuthError) Reset() {
	*x = AuthError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errz_v1_errz_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthError) ProtoMessage() {}

func (x *AuthError) ProtoReflect() protoreflect.Message {
	mi := &file_errz_v1_errz_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthError.ProtoReflect.Descriptor instead.
func (*AuthError) Descriptor() ([]byte, []int) {
	return file_errz_v1_errz_proto_rawDescGZIP(), []int{2}
}

func (x *AuthError) GetType() AuthError_ErrorType {
	if x != nil {
		return x.Type
	}
	return AuthError_TOKEN_EXPIRED
}

func (x *AuthError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthError) GetEnMessage() string {
	if x != nil {
		return x.EnMessage
	}
	return ""
}

var File_errz_v1_errz_proto protoreflect.FileDescriptor

var file_errz_v1_errz_proto_rawDesc = []byte{
	0x0a, 0x12, 0x65, 0x72, 0x72, 0x7a, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x72, 0x72, 0x7a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x65, 0x72, 0x72, 0x7a, 0x2e, 0x76, 0x31, 0x22, 0x5e, 0x0a,
	0x0d, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x65, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xb1, 0x01,
	0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x32, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x65, 0x72,
	0x72, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65,
	0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x65, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x35, 0x0a, 0x09, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x53, 0x10, 0x00, 0x12,
	0x06, 0x0a, 0x02, 0x44, 0x42, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x54, 0x45, 0x52,
	0x4e, 0x41, 0x4c, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x4b, 0x4f, 0x57, 0x4e, 0x10,
	0x0a, 0x22, 0x81, 0x02, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x30, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e,
	0x65, 0x72, 0x72, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65,
	0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x65, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x09, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x4f, 0x4b, 0x45,
	0x4e, 0x5f, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x54,
	0x4f, 0x4b, 0x45, 0x4e, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x01, 0x12, 0x13,
	0x0a, 0x0f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e,
	0x44, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x4e, 0x4f,
	0x54, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x0a, 0x12, 0x14, 0x0a, 0x10, 0x44, 0x45, 0x56,
	0x49, 0x43, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x0b, 0x12,
	0x14, 0x0a, 0x10, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x5f, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x10, 0x14, 0x42, 0x5e, 0x0a, 0x21, 0x69, 0x6e, 0x6b, 0x2e, 0x73, 0x66, 0x73,
	0x2e, 0x74, 0x69, 0x6e, 0x6b, 0x6c, 0x65, 0x72, 0x2e, 0x6d, 0x71, 0x74, 0x74, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x65, 0x72, 0x72, 0x7a, 0x2e, 0x76, 0x31, 0x42, 0x09, 0x45, 0x72, 0x72, 0x7a,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x69, 0x6e, 0x6b, 0x6c, 0x65, 0x72, 0x2f, 0x6d, 0x71, 0x74, 0x74,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x65, 0x72, 0x72, 0x7a, 0x2f, 0x76, 0x31, 0x3b, 0x65, 0x72,
	0x72, 0x7a, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_errz_v1_errz_proto_rawDescOnce sync.Once
	file_errz_v1_errz_proto_rawDescData = file_errz_v1_errz_proto_rawDesc
)

func file_errz_v1_errz_proto_rawDescGZIP() []byte {
	file_errz_v1_errz_proto_rawDescOnce.Do(func() {
		file_errz_v1_errz_proto_rawDescData = protoimpl.X.CompressGZIP(file_errz_v1_errz_proto_rawDescData)
	})
	return file_errz_v1_errz_proto_rawDescData
}

var file_errz_v1_errz_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_errz_v1_errz_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_errz_v1_errz_proto_goTypes = []interface{}{
	(ServerError_ErrorType)(0), // 0: errz.v1.ServerError.ErrorType
	(AuthError_ErrorType)(0),   // 1: errz.v1.AuthError.ErrorType
	(*ValidateError)(nil),      // 2: errz.v1.ValidateError
	(*ServerError)(nil),        // 3: errz.v1.ServerError
	(*AuthError)(nil),          // 4: errz.v1.AuthError
}
var file_errz_v1_errz_proto_depIdxs = []int32{
	0, // 0: errz.v1.ServerError.type:type_name -> errz.v1.ServerError.ErrorType
	1, // 1: errz.v1.AuthError.type:type_name -> errz.v1.AuthError.ErrorType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_errz_v1_errz_proto_init() }
func file_errz_v1_errz_proto_init() {
	if File_errz_v1_errz_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_errz_v1_errz_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_errz_v1_errz_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_errz_v1_errz_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_errz_v1_errz_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errz_v1_errz_proto_goTypes,
		DependencyIndexes: file_errz_v1_errz_proto_depIdxs,
		EnumInfos:         file_errz_v1_errz_proto_enumTypes,
		MessageInfos:      file_errz_v1_errz_proto_msgTypes,
	}.Build()
	File_errz_v1_errz_proto = out.File
	file_errz_v1_errz_proto_rawDesc = nil
	file_errz_v1_errz_proto_goTypes = nil
	file_errz_v1_errz_proto_depIdxs = nil
}
