// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.
import '../../http.dart';
import './const.dart';


class Role {
	
	int id = 0;
	
	String name = "";
	
	
	Future<void> saveRole(
		
	) async {
		var response = await D.instance.dio.post('$modelUrlPrefix/role/role/save-role', data: {
			"data": this,
			"args": {  }
		});
		if (response.data['code'] == 0) {
			var respModel = Role.fromJson(response.data['data']['data']);
			assign(respModel);
			
			
		} else {
			throw Exception(response.data['message']);
		}
	}
	
	Role();

	assign(Role other) {
		
		id = other.id;
		
		name = other.name;
		
	}

	Map<String, dynamic> toJson() {
		return {
			
			"id": id,
			
			"name": name,
			
		};
	}
	Role.fromJson(Map<String, dynamic> json) {
		
		id = json["id"];
		
		name = json["name"];
		
	}
}


