// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.
package route

func init() {
	
	routePathMap["/page/page/fetch-user"] = "pkg/model/page/page.go:15"
	routePathMap["/page/page_row/gen-row"] = "pkg/model/page/row.go:25"
	routePathMap["/page/page_row/gen-user"] = "pkg/model/page/row.go:48"
}

