// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.
package route
import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/tinkler/mqttadmin/pkg/jsonz/sjson"
	"github.com/tinkler/mqttadmin/pkg/model/page"
	"github.com/tinkler/mqttadmin/pkg/status"
	"github.com/tinkler/mqttadmin/pkg/model/user"
)

func RoutesPage(m *chi.Mux) {
	m.Route("/page", func(r chi.Router) {
		
		r.Post("/page/fetch-user", func(w http.ResponseWriter, r *http.Request) {
			m := Model[*page.Page, any]{}
			err := sjson.Bind(r, &m)
			if err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			}
			res := Res[*page.Page,[]*user.User]{Data:m.Data}
			res.Resp, err = m.Data.FetchUser(r.Context())
			
			if status.HttpError(w, err) {
				return
			}
			if sjson.HttpWrite(w, res) {
				return
			}

		})
	})
}
