// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.
package route

func init() {
	
	routePathMap["/permission/user_permission/save-permission"] = "pkg/model/permission/user_permission.go:18"
	routePathMap["/permission/user_permission/delete-permission"] = "pkg/model/permission/user_permission.go:28"
	routePathMap["/permission/permission/save-permission"] = "pkg/model/permission/permission.go:16"
	routePathMap["/permission/permission/delete-permission"] = "pkg/model/permission/permission.go:20"
	routePathMap["/permission/role_permission/save-permission"] = "pkg/model/permission/role_permission.go:18"
	routePathMap["/permission/role_permission/delete-permission"] = "pkg/model/permission/role_permission.go:25"
}

