// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.
package route
import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/tinkler/mqttadmin/pkg/jsonz/sjson"
	"github.com/tinkler/mqttadmin/pkg/model/role"
)

func RoutesRole(m *chi.Mux) {
	m.Route("/role", func(r chi.Router) {
		
		r.Post("/role/save-role", func(w http.ResponseWriter, r *http.Request) {
			m := Model[*role.Role, any]{}
			err := sjson.Bind(r, &m)
			if err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			}
			res := Res[struct{}]{}
			
			err = m.Data.SaveRole(r.Context())
			
			if err != nil {
				http.Error(w, err.Error(), http.StatusInternalServerError)
				return
			}
			w.Header().Set("Content-Type", "application/json")
			byt, _ := sjson.Marshal(res)
			_, _ = w.Write(byt)

		})
	})
}
